name: Run Selenium Script

on: [push]

jobs:
  build:
    runs-on: windows-latest  # Changed to windows-latest for Windows OS compatibility
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup Chrome WebDriver
      run: |
        options = webdriver.ChromeOptions()
        driver = webdriver.Chrome(options=options)
        
    - name: Run script
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}  # Accessing the secret
      run: python logging_info.py
