name: Run Selenium Script on Push

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pymongo

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1

      - name: Run the Selenium script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: logging_info.py



# name: Run Selenium Script

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest  
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
        
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
        
#     - name: Setup Chrome WebDriver
#       run: |
#         Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_win32.zip -OutFile chromedriver.zip
#         Expand-Archive chromedriver.zip -DestinationPath.
#         $env:PATH += ";$(Get-Location)"
 
#     - name: Run script
#       env:
#         MONGO_URI: ${{ secrets.MONGO_URI }}  # Accessing the secret
#       run: python logging_info.py
